name: CD - Continuous Deployment to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: fcg-pagamentos-api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/FCGPagamentos.API'
  DOTNET_VERSION: '8.0.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} -c Release -o ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/myapp
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/myapp
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        
    - name: Verify deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 API deployed to: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
