name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }
      - run: dotnet restore fcg-payments.sln
      - run: dotnet build -c Release --no-restore fcg-payments.sln
      - run: dotnet test -c Release --no-build || echo "no tests"
      - run: dotnet publish ./src/FCGPagamentos.API/FCGPagamentos.API.csproj -c Release -o ./out/api
      - uses: actions/upload-artifact@v4
        with: { name: api-publish, path: ./out/api }
