name: Trigger auto deployment for fcg-api-payments

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fcg-api-payments-AutoDeployTrigger-cd70a51d-69e6-44a7-806d-fab84c24e189.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.FCGAPIPAYMENTS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ca0c3c1a2875acr.azurecr.io
          registryUsername: ${{ secrets.FCGAPIPAYMENTS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FCGAPIPAYMENTS_REGISTRY_PASSWORD }}
          containerAppName: fcg-api-payments
          resourceGroup: rg-fcg-payments
          imageToBuild: ca0c3c1a2875acr.azurecr.io/fcg-api-payments:${{ github.sha }}
          
            

     

