name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1' # Toda segunda-feira às 2h
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Run security audit
      run: |
        dotnet list package --vulnerable
        dotnet restore --force-evaluate
        
    - name: Run dependency check
      run: |
        dotnet outdated --upgradeable
        dotnet list package --deprecated
        
    - name: Security scan completed
      run: |
        echo "🔒 Security scan completed successfully!"
        echo "📋 Check for any vulnerabilities or outdated packages above"
